version: '3.9'
services:
  web:
    build: 
      context: ./web
      dockerfile: Dockerfile.tomcat
    ports:
      - 80:80

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.spring
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: mysql:5.7
    env_file:
      - ./db/.env
    ports:
      - 3306:3306
